#
# Copyright Â© 2013-2018, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#logging:
#  loggers:
#    org.seedstack.netflix.hystrix.internal.CoffigHystrixDynamicProperties: TRACE

netflix:
  hystrix:
    properties:
      command.default.execution.isolation.thread.timeoutInMilliseconds: 100

feign:
  endpoints:
    org.seedstack.feign.fixtures.apis.TestAPI:
      baseUrl: ${web.runtime.baseUrl}feign
      logLevel: BASIC
      fallback: org.seedstack.feign.fixtures.TestFallback
      logger: feign.slf4j.Slf4jLogger
      hystrixWrapper: AUTO
    org.seedstack.feign.fixtures.apis.TimeoutAPI:
      baseUrl: ${web.runtime.baseUrl}feign
      logLevel: BASIC
      fallback: org.seedstack.feign.fixtures.TimeoutFallbackFactory
      logger: feign.slf4j.Slf4jLogger
      hystrixWrapper: AUTO
      connectTimeout: 5000
      readTimeout: 2000
    org.seedstack.feign.fixtures.apis.TestContractAPI:
      baseUrl: ${web.runtime.baseUrl}feign
      contract: org.seedstack.feign.fixtures.TestContract
      hystrixWrapper: DISABLED
    org.seedstack.feign.fixtures.apis.HystrixEnabledAPI:
      baseUrl: ${web.runtime.baseUrl}feign
      logLevel: BASIC
      fallback: org.seedstack.feign.fixtures.TestFallback
      hystrixWrapper: ENABLED
    org.seedstack.feign.fixtures.apis.HystrixDisabledAPI:
      baseUrl: ${web.runtime.baseUrl}feign
      logLevel: BASIC
      hystrixWrapper: DISABLED  
    org.seedstack.feign.fixtures.apis.TargetableAPI:
      baseUrl: http://ignore.this.is.overriden
      logLevel: BASIC
      target: org.seedstack.feign.fixtures.TestTarget
      hystrixWrapper: DISABLED
      